<?php
/**
 * DocumentInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sufel\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SUFEL
 *
 * Sufel API for Companies.
 *
 * OpenAPI spec version: 2.0
 * Contact: giansalex@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sufel\Client;

/**
 * DocumentInfoTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentInfo
 * @package     Sufel\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentInfo"
     */
    public function testDocumentInfo()
    {
    }

    /**
     * Test attribute "tipo"
     */
    public function testPropertyTipo()
    {
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
    }

    /**
     * Test attribute "correlativo"
     */
    public function testPropertyCorrelativo()
    {
    }
}
