<?php
/**
 * DocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sufel\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SUFEL
 *
 * Sufel API for Companies.
 *
 * OpenAPI spec version: 2.0
 * Contact: giansalex@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sufel\Client;

/**
 * DocumentTest Class Doc Comment
 *
 * @category    Class
 * @description Document
 * @package     Sufel\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Document"
     */
    public function testDocument()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "emisor"
     */
    public function testPropertyEmisor()
    {
    }

    /**
     * Test attribute "tipo"
     */
    public function testPropertyTipo()
    {
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
    }

    /**
     * Test attribute "correlativo"
     */
    public function testPropertyCorrelativo()
    {
    }

    /**
     * Test attribute "fecha"
     */
    public function testPropertyFecha()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "cliente_tipo"
     */
    public function testPropertyClienteTipo()
    {
    }

    /**
     * Test attribute "cliente_doc"
     */
    public function testPropertyClienteDoc()
    {
    }

    /**
     * Test attribute "cliente_nombre"
     */
    public function testPropertyClienteNombre()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "baja"
     */
    public function testPropertyBaja()
    {
    }

    /**
     * Test attribute "xml"
     */
    public function testPropertyXml()
    {
    }

    /**
     * Test attribute "pdf"
     */
    public function testPropertyPdf()
    {
    }
}
