<?php
/**
 * CompanyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sufel\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SUFEL
 *
 * Sufel API for Companies.
 *
 * OpenAPI spec version: 2.0
 * Contact: giansalex@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sufel\Client;

use Sufel\Client\Api\CompanyApi;
use \Sufel\Client\Configuration;
use \Sufel\Client\ApiException;
use Sufel\Client\Model\CompanyCredential;
use \Sufel\Client\ObjectSerializer;

/**
 * CompanyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sufel\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompanyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addDocument
     *
     * Agrega nuevo documento..
     *
     */
    public function testAddDocument()
    {
    }

    /**
     * Test case for authCompany
     *
     * Autentificacion de Empresa.
     *
     */
    public function testAuthCompany()
    {
    }

    /**
     * Test case for changePassword
     *
     * Cambia la contraseña de la Empresa.
     *
     */
    public function testChangePassword()
    {
    }

    /**
     * Test case for creteCompany
     *
     * Crea nueva Empresa.
     *
     */
    public function testCreteCompany()
    {
    }

    /**
     * Test case for darBajaDocument
     *
     * Da de baja documento..
     *
     */
    public function testDarBajaDocument()
    {
    }

    /**
     * Test case for getDocuments
     *
     * Lista los documentos del emisor.
     *
     */
    public function testGetDocuments()
    {
    }
}
